### ISSUE TITLE
 _Image.toByteData.<anonymous closure>.<anonymous closure> (dart:ui/painting.dart:1959:25)

### ISSUE THREAD

**Issue by illmushka** [SachinGanesh/screenshot#145]
Flutter 3.10.0
Screenshot version 2.0.0
IOS 16.2

#0      _Image.toByteData.<anonymous closure>.<anonymous closure> (dart:ui/painting.dart:1959:25)
Unhandled Exception: Exception: operation failed
#0      ScreenshotController.capture.<anonymous closure> (package:screenshot/screenshot.dart:61:9)
<asynchronous suspension>

capture method does not work
works fine on android but not on IOS

**Comment by kvenn** [comment]
I'm also getting this error. Only seems to happen sometimes with certain widgets that include images
