### ISSUE TITLE
Not work on Android 14

### ISSUE THREAD

**Issue by QuDaMyker** [SachinGanesh/screenshot#192]
Stack trace:
I/flutter (10665): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (10665): │ #0   ScreenshotController.captureAndSave (package:screenshot/screenshot.dart:39:40)
I/flutter (10665): │ #1   <asynchronous suspension>
I/flutter (10665): │ #2   TicketOrder._createAndSaveImage (package:fstore/screens/order_history/views/ticket_order.dart:806:5)
I/flutter (10665): │ #3   <asynchronous suspension>
I/flutter (10665): │ #4   TicketOrder.build.<anonymous closure>.<anonymous closure> (package:fstore/screens/order_history/views/ticket_order.dart:137:29)
I/flutter (10665): │ #5   <asynchronous suspension>

**Comment by Asifkp123** [comment]
do you clear the issue??
