### ISSUE TITLE
Flutter GoogleMaps RepaintsBoundary. toImage() Crashes on Web

### ISSUE THREAD

**Issue by tolotrasamuel** [SachinGanesh/screenshot#55]
Steps to reproduce:

1) On Flutter Web, Wrap Flutter Google Maps in a RepaintBoundary

Like so:

      @override
      Widget build(BuildContext context) {
        return RepaintBoundary(
          key: ScreenShotable.previewContainer,
          child: widget.child,
        );
      }

 Usage:

    final img = await screenshotController.captureAsUiImage(
            Container(
              height: 100,
              width: 100,
              color: Colors.brown,
              child: GoogleMap(
                initialCameraPosition: CameraPosition(
                  target: FlitLatLng(-20.1020344, 57.5621812999999).toLatLng(),
                  zoom: 13.0,
                ),
                rotateGesturesEnabled: false,
                tiltGesturesEnabled: false,
                // markers: Set<Marker>.of(controller.markers.values),
              ),
            ),
            delay: Duration(seconds: 6));

ScreenshotControllers.captureAsUiImage 

    RenderRepaintBoundary boundary =
        this.view!.context.findRenderObject() as RenderRepaintBoundary;
    ui.Image image = await boundary.toImage(pixelRatio: pxRatio); // crash here

Actual: 

    Error: Unexpected null value.
        at Object.throw_ [as throw] (http://localhost:49196/dart_sdk.js:5037:11)
        at Object.nullCheck (http://localhost:49196/dart_sdk.js:5362:30)
        at _engine.PlatformViewLayer.new.preroll (http://localhost:49196/dart_sdk.js:135222:12)
        at _engine.OffsetEngineLayer.new.prerollChildren (http://localhost:49196/dart_sdk.js:134614:15)
        at _engine.OffsetEngineLayer.new.preroll (http://localhost:49196/dart_sdk.js:134881:35)
        at _engine.OffsetEngineLayer.new.prerollChildren (http://localhost:49196/dart_sdk.js:134614:15)
        at _engine.OffsetEngineLayer.new.preroll (http://localhost:49196/dart_sdk.js:134881:35)
        at _engine.TransformEngineLayer.new.prerollChildren (http://localhost:49196/dart_sdk.js:134614:15)
        at _engine.TransformEngineLayer.new.preroll (http://localhost:49196/dart_sdk.js:134881:35)
        at _engine.RootLayer.new.prerollChildren (http://localhost:49196/dart_sdk.js:134614:15)
        at _engine.RootLayer.new.preroll (http://localhost:49196/dart_sdk.js:134609:31)
        at _engine.LayerTree.new.flatten (http://localhost:49196/dart_sdk.js:135508:22)
        at _engine.LayerScene.new.toImage (http://localhost:49196/dart_sdk.js:135263:36)
        at layer$.OffsetLayer.new.toImage (http://localhost:49196/packages/flutter/src/rendering/layer.dart.js:1327:30)
        at toImage.next (<anonymous>)
        at runBody (http://localhost:49196/dart_sdk.js:37393:34)
        at Object._async [as async] (http://localhost:49196/dart_sdk.js:37424:7)
        at layer$.OffsetLayer.new.toImage (http://localhost:49196/packages/flutter/src/rendering/layer.dart.js:1318:20)
        at proxy_box.RenderRepaintBoundary.new.toImage (http://localhost:49196/packages/flutter/src/rendering/proxy_box.dart.js:3096:26)
        at captureFromWidget (http://localhost:49196/packages/screenshot/screenshot.dart.js:242:44)
        at captureFromWidget.next (<anonymous>)
        at http://localhost:49196/dart_sdk.js:37374:33
        at _RootZone.runUnary (http://localhost:49196/dart_sdk.js:37245:59)
        at _FutureListener.thenAwait.handleValue (http://localhost:49196/dart_sdk.js:32501:29)
        at handleValueCallback (http://localhost:49196/dart_sdk.js:33028:49)
        at Function._propagateToListeners (http://localhost:49196/dart_sdk.js:33066:17)
        at _Future.new.[_complete] (http://localhost:49196/dart_sdk.js:32906:25)
        at http://localhost:49196/dart_sdk.js:32085:30
        at internalCallback (http://localhost:49196/dart_sdk.js:24224:11)

Expected:

No crash. Even better if we get the screenshot of the map. 
On Mobile, we get blank screen.

Further debugging:

I tried with my own code above and even with the https://pub.dev/packages/screenshot package. Same result

If you have any clue on what the error above means, I would appreciate, even a small comment. It will help me find a workaround

**Comment by tolotrasam** [comment]
Nevermind I found a solution

**Comment by ritheshSalyan** [comment]
Closing in favour of https://github.com/SachinGanesh/screenshot/issues/62
