### ISSUE TITLE
Cannot clone a disposed image

### ISSUE THREAD

**Issue by raulmabe** [SachinGanesh/screenshot#75]
When using this plugin I get the following error sometimes.

```
Bad state: Cannot clone a disposed image.
      The clone() method of a previously-disposed Image was called. Once an Image object has been disposed, it can no longer be used to create handles, as the underlying data may have been released.
[log] #0      Image.clone (dart:ui/painting.dart:1758:7)
#1      ImageInfo.clone
package:flutter/…/painting/image_stream.dart:51
#2      ImageStreamCompleter.setImage
package:flutter/…/painting/image_stream.dart:618
#3      _rootRunUnary (dart:async/zone.dart:1362:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
```

I suspect it's caused by the `delay` property, as it's trying to screenshot from a widget that has already disposed...

Plugin version:  `screenshot: ^1.2.3`

**Comment by ritheshSalyan** [comment]
@raulmabe  Can we get some sample code to test?

**Comment by raulmabe** [comment]
I updated my post to add sample code, although is incomplete as my code has a lot of unrelated business logic and can't take time now to refactor it

**Comment by raulmabe** [comment]
I am also getting this error when navigating across pages:
```

'package:flutter/src/painting/image_stream.dart': Failed assertion: line 122 pos 12: '(image.debugGetOpenHandleStackTraces()?.length ?? 1) > 0': is not true.


#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      ImageInfo.dispose (package:flutter/src/painting/image_stream.dart:122:12)
#3      ImageStreamCompleter._maybeDispose (package:flutter/src/painting/image_stream.dart:576:20)
#4      ImageStreamCompleterHandle.dispose (package:flutter/src/painting/image_stream.dart:447:17)
#5      _CachedImageBase.dispose.<anonymous closure> (package:flutter/src/painting/image_cache.dart:627:15)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#9      _rootRun (dart:async/zone.dart:1354:13)
#10     _CustomZone.run (dart:async/zone.dart:1258:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#12     _invoke (dart:ui/hooks.dart:163:10)
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#14     _drawFrame (dart:ui/hooks.dart:126:31)

#0      new Image._.<anonymous closure> (dart:ui/painting.dart:1647:32)
#1      new Image._ (dart:ui/painting.dart:1649:6)
#2      Codec.getNextFrame.<anonymous closure> (dart:ui/painting.dart:1994:24)
```
