### ISSUE TITLE
Null value on Flutter WEB | unable to capture

### ISSUE THREAD

**Issue by HKTareen** [SachinGanesh/screenshot#95]
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:58352/dart_sdk.js:5063:11)
    at Object.nullCheck (http://localhost:58352/dart_sdk.js:5390:30)
    at _engine.PlatformViewLayer.new.preroll (http://localhost:58352/dart_sdk.js:147069:12)
    at _engine.OffsetEngineLayer.new.prerollChildren (http://localhost:58352/dart_sdk.js:146409:15)
    at _engine.OffsetEngineLayer.new.preroll (http://localhost:58352/dart_sdk.js:146705:35)
    at _engine.OffsetEngineLayer.new.prerollChildren (http://localhost:58352/dart_sdk.js:146409:15)
    at _engine.OffsetEngineLayer.new.preroll (http://localhost:58352/dart_sdk.js:146705:35)
    at _engine.OffsetEngineLayer.new.prerollChildren (http://localhost:58352/dart_sdk.js:146409:15)
    at _engine.OffsetEngineLayer.new.preroll (http://localhost:58352/dart_sdk.js:146705:35)
    at _engine.TransformEngineLayer.new.prerollChildren (http://localhost:58352/dart_sdk.js:146409:15)
    at _engine.TransformEngineLayer.new.preroll (http://localhost:58352/dart_sdk.js:146705:35)
    at _engine.RootLayer.new.prerollChildren (http://localhost:58352/dart_sdk.js:146409:15)
    at _engine.RootLayer.new.preroll (http://localhost:58352/dart_sdk.js:146404:31)
    at _engine.LayerTree.new.flatten (http://localhost:58352/dart_sdk.js:147359:22)
    at _engine.LayerScene.new.toImage (http://localhost:58352/dart_sdk.js:147115:36)
    at layer$.OffsetLayer.new.toImage (http://localhost:58352/packages/flutter/src/rendering/layer.dart.lib.js:1429:30)
    at toImage.next (<anonymous>)
    at runBody (http://localhost:58352/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:58352/dart_sdk.js:40242:7)
    at layer$.OffsetLayer.new.toImage (http://localhost:58352/packages/flutter/src/rendering/layer.dart.lib.js:1420:20)
    at proxy_box.RenderRepaintBoundary.new.toImage (http://localhost:58352/packages/flutter/src/rendering/proxy_box.dart.lib.js:3345:26)
    at screenshot.ScreenshotController.new.<anonymous> (http://localhost:58352/packages/screenshot/screenshot.dart.lib.js:174:39)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:58352/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:58352/dart_sdk.js:40242:7)
    at http://localhost:58352/packages/screenshot/screenshot.dart.lib.js:162:68
    at http://localhost:58352/dart_sdk.js:34537:33
    at internalCallback (http://localhost:58352/dart_sdk.js:26215:11)
    
Flutter SDK 2.8.1

**Comment by SaiSantosh-GetOnForm** [comment]
This happens only when image is part of screenshot. It works for other widgets

**Comment by HKTareen** [comment]
@SaiSantosh-GetOnForm image is not a part of screenshot i just wrapped my WebView widget with the screenshot and called the capture method.

**Comment by caleb654** [comment]
I'm also getting this issue.

**Comment by YohanWadia** [comment]
Yeah any help here... Im not able to capture my webview on flutter web either. Im using  **webview_flutter_web: ^0.1.0+4**

**Comment by AJAY-AGARIAN** [comment]
Flutter web view isn't being captured by any screenshot package so far, seems like it's a core flutter issue. There are issues raised on the same in flutter's GitHub profile. But there has to be some solution.
